-- MySQL Script generated by MySQL Workbench
-- Mon Apr 25 23:05:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pf_super
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pf_super` ;

-- -----------------------------------------------------
-- Schema pf_super
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pf_super` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema pf_supermercado
-- -----------------------------------------------------
SHOW WARNINGS;
USE `pf_super` ;

-- -----------------------------------------------------
-- Table `Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Clientes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(60) NULL,
  `apellidos` VARCHAR(60) NULL,
  `NIT` VARCHAR(12) NULL,
  `genero` BIT NULL,
  `telefono` VARCHAR(25) NULL,
  `correo_electronico` VARCHAR(45) NULL,
  `fechaingreso` DATETIME NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Compras` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Compras` (
  `idCompra` INT NOT NULL AUTO_INCREMENT,
  `no_orden_compra` INT NULL,
  `idproveedor` INT NULL,
  `fecha_orden` DATE NULL,
  `fechaingreso` DATETIME NULL,
  PRIMARY KEY (`idCompra`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Compras_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Compras_detalle` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Compras_detalle` (
  `idCompras_detalle` BIGINT NOT NULL AUTO_INCREMENT,
  `idCompra` INT NULL,
  `idProducto` INT NULL,
  `canitdad` VARCHAR(45) NULL,
  `precio_costo_unitario` DECIMAL(8,2) NULL,
  PRIMARY KEY (`idCompras_detalle`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Empleados` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Empleados` (
  `idempleado` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(60) NULL,
  `apellidos` VARCHAR(60) NULL,
  `direccion` VARCHAR(60) NULL,
  `telefono` VARCHAR(25) NULL,
  `DPI` VARCHAR(15) NULL,
  `genero` BIT NULL,
  `fecha_nacimiento` DATE NULL,
  `idPuesto` SMALLINT NULL,
  `fecha_inicio_labores` DATE NULL,
  `fechaingreso` DATETIME NULL,
  PRIMARY KEY (`idempleado`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Marcas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marcas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Marcas` (
  `idMarca` SMALLINT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(50) NULL,
  PRIMARY KEY (`idMarca`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Productos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Productos` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `producto` VARCHAR(45) NULL,
  `idMarca` SMALLINT NULL,
  `Descripcion` VARCHAR(100) NULL,
  `Imagen` VARCHAR(30) NULL,
  `precio_costo` DECIMAL(8,2) NULL,
  `precio_venta` DECIMAL(8,2) NULL,
  `existencia` INT NULL,
  `fecha_ingreso` DATETIME NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Proveedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Proveedores` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Proveedores` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `proveedor` VARCHAR(60) NULL,
  `nit` VARCHAR(12) NULL,
  `direccion` VARCHAR(80) NULL,
  `telefono` VARCHAR(25) NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ventas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Ventas` (
  `idVentas` INT NOT NULL AUTO_INCREMENT,
  `nofactura` INT NULL,
  `serie` VARCHAR(1) NULL,
  `fechafactura` DATE NULL,
  `idcliente` INT NULL,
  `idempleado` INT NULL,
  `fechaingreso` DATETIME NULL,
  PRIMARY KEY (`idVentas`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Ventas_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ventas_detalle` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Ventas_detalle` (
  `idVentas_detalle` BIGINT NOT NULL AUTO_INCREMENT,
  `idVentas` INT NULL,
  `idproducto` INT NULL,
  `cantidad` VARCHAR(45) NULL,
  `precio_unitario` DECIMAL(8,2) NULL,
  PRIMARY KEY (`idVentas_detalle`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `puestos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `puestos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `puestos` (
  `idpuesto` SMALLINT NOT NULL AUTO_INCREMENT,
  `puesto` VARCHAR(50) NULL,
  PRIMARY KEY (`idpuesto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `table1` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `table1` (
)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
